### ISSUE TITLE
cannot read property 'id' of null

### ISSUE THREAD

**Issue by b-e-y** [Vordlex/mudae-sniper#1]
![image](https://user-images.githubusercontent.com/56668359/141693426-94b79648-f25e-4c27-ace2-693448f499a3.png)
i ran into this error

**Comment by beyabay** [comment]
> ![image](https://user-images.githubusercontent.com/56668359/141693426-94b79648-f25e-4c27-ace2-693448f499a3.png) i ran into this error

i also doubled check my token

**Comment by Vordlex** [comment]
This is not a problem with token, it manages to connect to your account but it gives some error, could you tell me if this error occurs right after you give the initialization command (node index.js) or if it occurs sometime later?
